In [5]:
import numpy as np
from scipy.optimize import curve_fit

In [215]:
x = np.linspace(1,100, num=100)
x

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [216]:
y = x+x**2#np.round(np.log(x)*10) + 1
# y = x + np.log(x)
y

array([2.000e+00, 6.000e+00, 1.200e+01, 2.000e+01, 3.000e+01, 4.200e+01,
       5.600e+01, 7.200e+01, 9.000e+01, 1.100e+02, 1.320e+02, 1.560e+02,
       1.820e+02, 2.100e+02, 2.400e+02, 2.720e+02, 3.060e+02, 3.420e+02,
       3.800e+02, 4.200e+02, 4.620e+02, 5.060e+02, 5.520e+02, 6.000e+02,
       6.500e+02, 7.020e+02, 7.560e+02, 8.120e+02, 8.700e+02, 9.300e+02,
       9.920e+02, 1.056e+03, 1.122e+03, 1.190e+03, 1.260e+03, 1.332e+03,
       1.406e+03, 1.482e+03, 1.560e+03, 1.640e+03, 1.722e+03, 1.806e+03,
       1.892e+03, 1.980e+03, 2.070e+03, 2.162e+03, 2.256e+03, 2.352e+03,
       2.450e+03, 2.550e+03, 2.652e+03, 2.756e+03, 2.862e+03, 2.970e+03,
       3.080e+03, 3.192e+03, 3.306e+03, 3.422e+03, 3.540e+03, 3.660e+03,
       3.782e+03, 3.906e+03, 4.032e+03, 4.160e+03, 4.290e+03, 4.422e+03,
       4.556e+03, 4.692e+03, 4.830e+03, 4.970e+03, 5.112e+03, 5.256e+03,
       5.402e+03, 5.550e+03, 5.700e+03, 5.852e+03, 6.006e+03, 6.162e+03,
       6.320e+03, 6.480e+03, 6.642e+03, 6.806e+03, 

In [219]:
def obj_func(x, p1, p2, p3, p4):
    
#     f = p1*x+x**p2+p3

    f = p1 + x**p2 + x**p3 + x**p4
    
    return f

In [220]:
res = curve_fit(f=obj_func, xdata=x, ydata=y)
res[0]

array([-1.00001946e+00,  1.08676793e-05,  2.00000000e+00,  9.99999817e-01])

In [221]:
def obj_func_fitted(x):
    
    print(x)
#     return res[0][0]*x+x**res[0][1]+res[0][2]

    return res[0][0] + x**res[0][1] + x**res[0][2] + x**res[0][3]

In [222]:
idx = 1
print(obj_func_fitted(x[idx]))
print(y[idx])

2.0
5.9999878242871505
6.0


In [150]:
# y[1]

In [151]:
# func1 = np.polyfit(x,y, deg=2)

In [152]:
# params = func1

In [153]:
# params

In [202]:
y_hat = 0

for i, param in enumerate(params):
    
    y_hat = y_hat + param * x[3]**i  
    
y_hat

1.2181818181819437