In [1]:
import numpy as np
from scipy.optimize import minimize

### Non Linear Programming

min x1x4(x1+x2+x3)+x3

s.t. x1x2x3x4 >= 25
 
x1^2 + x2^2 + x3^2 + x4^2 = 40

1 <= x1,x2,x3,x4 <= 5

x0 = (1,5,5,1)

In [2]:
def objective(x):
    
    x1 = x[0]
    x2 = x[1]
    x3 = x[2]
    x4 = x[3]
    
    return x1*x4*(x1+x2+x3)+x3

In [3]:
def constraint_1(x):
    
    return x[0]*x[1]*x[2]*x[3]-25.0

In [4]:
def constraint_2(x):
    
    sum_sq = 40
    
    for i in range(4):
        sum_sq = sum_sq - x[i]**2
        
    return sum_sq

In [5]:
x0 = [1,5,5,1]

In [6]:
print(objective(x0))

16


In [7]:
b = (1.0,5.0)
bnds = (b,b,b,b)

In [8]:
con1 = {'type':'ineq', 'fun':constraint_1}
con2 = {'type':'eq', 'fun':constraint_2}

cons = [con1, con2]

In [9]:
solution = minimize(
    fun = objective,
    x0 = x0,
    args=(),
    method='SLSQP',
    jac=None,
    hess=None,
    hessp=None,
    bounds=bnds,
    constraints=cons,
    tol=None,
    callback=None,
    options={'maxiter':10},
)

In [10]:
if solution.success:
    print(solution)

     fun: 17.01401724563517
     jac: array([14.57227015,  1.37940764,  2.37940764,  9.56415057])
 message: 'Optimization terminated successfully'
    nfev: 25
     nit: 5
    njev: 5
  status: 0
 success: True
       x: array([1.        , 4.7429961 , 3.82115462, 1.37940765])


In [15]:
from scipy.optimize import linprog

In [16]:
# Object function
c = [-1, 4] # -x +4y

In [19]:
# Constraints

A_u = np.array([[3,2],[1,5]])
b_u = np.array([10, 10])

In [21]:
A_u

array([[3, 2],
       [1, 5]])

In [22]:
b_u

array([10, 10])

In [20]:
# Bounds
b = (0, 10) # 0 <= x <= 10

In [23]:
res = linprog(c, A_ub=A_u, b_ub=b_u, bounds=(b,b), integrality=[1,1])

In [24]:
res.fun

-3.0

In [25]:
res.x

array([3., 0.])